# Create image based on the official Node 11 image from dockerhub
FROM node:20-alpine as builder

ENV NODE_ENV development

ENV APP_ROOT /app

# Create a directory where our app will be placed
RUN mkdir -p $APP_ROOT

# Change directory so that our commands run inside this new directory
WORKDIR $APP_ROOT

# Copy dependency definitions
COPY package.json $APP_ROOT


# Install dependecies
RUN npm install

COPY . .

RUN npm run build

#nginx
FROM nginx:1.19.2-alpine

RUN rm -rf /usr/share/nginx/html/*

COPY --from=builder /app/dist/ /usr/share/nginx/html/

RUN rm -rf /etc/nginx/conf.d/default.conf

COPY --from=builder /app/default.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
