# @format

version: "3.8"

services:
  database:
    container_name: database
    image: postgres:latest
    volumes:
      - ./volume/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: postgres

  backend:
    container_name: backend
    build: backend
    ports:
      - "3000:3000"
    depends_on:
      - database
    volumes:
      - ./backend:/app
    environment:
      NODE_ENV: development
      DATABASE_URL: postgresql://admin:admin@database:5432/postgres

  frontend:
    container_name: frontend
    build: frontend
    ports:
      - "5173:80"
    depends_on:
      - backend
