FROM node:20-alpine

ENV APP_ROOT /app

WORKDIR $APP_ROOT
COPY . $APP_ROOT

RUN rm -rf node_modules dist

RUN npm install -g pnpm
RUN pnpm install
RUN npx prisma generate
CMD npx prisma migrate dev --name init && pnpm start:dev
EXPOSE 3000
